chore: test error

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -140,6 +140,7 @@ build_preview:
     - make config
     - ./node_modules/.bin/jest --testPathPattern=assets/scripts/tests/
     - yarn run prebuild
+    - exit 1
     - build_site
     # remove service_checks json as we don't need to s3 push that..
     - rm -rf data/service_checks
@@ -149,7 +150,7 @@ build_preview:
     - notify_slack.py  "Your branch ${CI_COMMIT_REF_NAME} is ready for preview. <${CI_PROJECT_URL}/pipelines/${CI_PIPELINE_ID}| checks running>." --status="#31b834" --previewSite="true"
     - ci_pass_step "${CI_PROJECT_NAME}-${CI_JOB_NAME}" # run at completion of job, if job fails at any point prior this won't run
   artifacts:
-    when: on_success
+    when: always
     paths:
       - ${ARTIFACT_RESOURCE}
       - ./integrations_data
@@ -158,11 +159,11 @@ build_preview:
       - .htmltest.yml
       - ./logs
       - ./public/redirects.txt
+      - $PREVIEW_ERROR_LOG
   after_script:
     - |
-      if [[ -s $PREVIEW_ERROR_LOG && $CI_JOB_STATUS != 'success' ]]; then
+      if [ -s $PREVIEW_ERROR_LOG && $CI_JOB_STATUS != 'success' ]; then
         echo "Error Detected: $(cat $PREVIEW_ERROR_LOG)";
-        notify_slack.py ":siren: A gitlab job for your branch has failed with the following error: $(tail -n 10 preview_error.log)" --status="#ab0000" --previewSite="false" --link="${CI_PIPELINE_URL}" --buttonContent="Gitlab Pipeline :looking:";
       fi # Output the error to the console
   interruptible: true
 
@@ -527,8 +528,13 @@ failure_notification_preview:
   environment: "preview"
   variables:
     GIT_STRATEGY: none
-    SLACK_MESSAGE: ":siren: A gitlab job for your branch has failed due to an error, please check your pipeline" # Safety in case the error log is empty
   script:
+    - |
+      if [ -s preview_error.log ]; then
+        SLACK_MESSAGE=":siren: A gitlab job for your branch has failed with the following error: $(tail -n 10 preview_error.log)";
+      else
+        SLACK_MESSAGE=":siren: A gitlab job for your branch has failed due to an error, please check your pipeline"; # Safety in case the error log is empty
+      fi
     - notify_slack.py "${SLACK_MESSAGE}" --status="#ab0000" --previewSite="false" --link="${CI_PIPELINE_URL}" --buttonContent="Gitlab Pipeline :looking:"
   rules:
     - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ $PREVIEW_PATTERN
